name: Benchmarks (CPU sanity)

on:
  push:
  pull_request:

jobs:
  cpu_sanity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run small CPU benchmark
        run: |
          python benchmarks/run_benchmarks.py --backend pytorch --model distilgpt2 --device cpu --dtype float32 --batch-size 1 --prompt-tokens 64 --new-tokens 32 --warmup-runs 0 --runs 1
